"""first

Revision ID: e07a6f1a3439
Revises: 
Create Date: 2021-01-12 14:01:20.251578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07a6f1a3439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regattas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yachtclass', sa.String(), nullable=True),
    sa.Column('regattaname', sa.String(), nullable=True),
    sa.Column('regattastartdate', sa.Date(), nullable=True),
    sa.Column('regattaenddate', sa.Date(), nullable=True),
    sa.Column('regattalocation', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regattas_id'), 'regattas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regattas_id'), table_name='regattas')
    op.drop_table('regattas')
    # ### end Alembic commands ###
